# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1448, 912)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color:#041423 ;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #041423;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: inset;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #3d85c6 ;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #041423;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #041423;\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #041423;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #2986cc ;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 2px;\n"
"    background-color: #041423;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #4598e2 ;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #4598e2 ;\n"
"    padding-bottom: 1px;\n"
"    background-color: #041423;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #808086;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #041423;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: #a9b7c6;\n"
"    background:#041423;\n"
"    selection-background-color:#007b50;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"QLabel {\n"
"    color: #a9b7c6;\n"
"}\n"
"\n"
"\n"
"\n"
"QMenuBar {\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #a9b7c6;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"      background: #1e1d23;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background:#1e1d23;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: #04b97f;\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #FFFFFF;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu{\n"
"    background-color:#1e1d23;\n"
"}\n"
"\n"
"\n"
"QCheckBox {\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:#041423;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #4598e2  ;\n"
"    color: #4598e2 ;\n"
"    background-color: #4598e2  ;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #4598e2  ;\n"
"    color: #4598e2  ;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"QTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QComboBox {\n"
"    color: #a9b7c6;    \n"
"    background: #041423;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #041423;\n"
"    color: #a9b7c6;\n"
"    selection-background-color: #041423;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #a9b7c6;    \n"
"    background: #041423;\n"
"    selection-color: #FFFFFF;\n"
"    selection-background-color: #041423;\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color: #a9b7c6;    \n"
"    background: #041423;\n"
"}\n"
"QFontComboBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #041423;\n"
"}\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color: #041423;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #4598e2;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 14px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #4598e2;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #04b97f;\n"
"}\n"
"QGroupBox {\n"
"    border:1px solid #3A3939;\n"
"    border-radius: 2px;\n"
"    margin-top: 20px;\n"
"    background-color: #1a3e5e    ;\n"
"    moz-box-shadow: 1px 1px 3px 2px #244258;\n"
"      webkit-box-shadow: 1px 1px 3px 2px #244258;\n"
"      box-shadow:         1px 1px 3px 2px #244258;\n"
"    color: silver;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setVerticalSpacing(45)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 0, 1, 1)
        self.label_MainWindow_title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_MainWindow_title.setFont(font)
        self.label_MainWindow_title.setTabletTracking(False)
        self.label_MainWindow_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_MainWindow_title.setLineWidth(14)
        self.label_MainWindow_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_MainWindow_title.setObjectName("label_MainWindow_title")
        self.gridLayout_9.addWidget(self.label_MainWindow_title, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setHorizontalSpacing(45)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_graph1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_graph1.setMinimumSize(QtCore.QSize(650, 350))
        self.groupBox_graph1.setMaximumSize(QtCore.QSize(16777215, 450))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox_graph1.setFont(font)
        self.groupBox_graph1.setMouseTracking(False)
        self.groupBox_graph1.setTabletTracking(True)
        self.groupBox_graph1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox_graph1.setAutoFillBackground(False)
        self.groupBox_graph1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_graph1.setFlat(False)
        self.groupBox_graph1.setObjectName("groupBox_graph1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_graph1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalScrollBar_L = QtWidgets.QScrollBar(self.groupBox_graph1)
        self.verticalScrollBar_L.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_L.setObjectName("verticalScrollBar_L")
        self.gridLayout_5.addWidget(self.verticalScrollBar_L, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalScrollBar_L = QtWidgets.QScrollBar(self.groupBox_graph1)
        self.horizontalScrollBar_L.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_L.setObjectName("horizontalScrollBar_L")
        self.gridLayout_2.addWidget(self.horizontalScrollBar_L, 1, 0, 1, 1)
        self.plotWidget_L = PlotWidget(self.groupBox_graph1)
        self.plotWidget_L.setObjectName("plotWidget_L")
        self.gridLayout_2.addWidget(self.plotWidget_L, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_graph1, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 0, 1, 1, 1)
        self.groupBox_graph2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_graph2.sizePolicy().hasHeightForWidth())
        self.groupBox_graph2.setSizePolicy(sizePolicy)
        self.groupBox_graph2.setMinimumSize(QtCore.QSize(650, 350))
        self.groupBox_graph2.setMaximumSize(QtCore.QSize(16777215, 450))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        self.groupBox_graph2.setFont(font)
        self.groupBox_graph2.setTabletTracking(True)
        self.groupBox_graph2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox_graph2.setAutoFillBackground(False)
        self.groupBox_graph2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_graph2.setFlat(False)
        self.groupBox_graph2.setObjectName("groupBox_graph2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_graph2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.verticalScrollBar_R = QtWidgets.QScrollBar(self.groupBox_graph2)
        self.verticalScrollBar_R.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_R.setObjectName("verticalScrollBar_R")
        self.gridLayout_23.addWidget(self.verticalScrollBar_R, 0, 0, 1, 1)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.plotWidget_R = PlotWidget(self.groupBox_graph2)
        self.plotWidget_R.setObjectName("plotWidget_R")
        self.gridLayout_24.addWidget(self.plotWidget_R, 0, 0, 1, 1)
        self.horizontalScrollBar_R = QtWidgets.QScrollBar(self.groupBox_graph2)
        self.horizontalScrollBar_R.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_R.setObjectName("horizontalScrollBar_R")
        self.gridLayout_24.addWidget(self.horizontalScrollBar_R, 1, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_24, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_graph2, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setVerticalSpacing(55)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setHorizontalSpacing(25)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.pushButton_export = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_export.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/export icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_export.setIcon(icon)
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout_22.addWidget(self.pushButton_export, 0, 0, 1, 1)
        self.checkBox_linkGraphs = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_linkGraphs.setMinimumSize(QtCore.QSize(69, 22))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.checkBox_linkGraphs.setFont(font)
        self.checkBox_linkGraphs.setObjectName("checkBox_linkGraphs")
        self.gridLayout_22.addWidget(self.checkBox_linkGraphs, 0, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_22, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem4, 0, 0, 1, 1)
        self.gridLayout_33.addLayout(self.gridLayout_25, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setHorizontalSpacing(45)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_55 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setVerticalSpacing(30)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setVerticalSpacing(20)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setHorizontalSpacing(7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.pushButton_L_zoomOut = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_L_zoomOut.setFont(font)
        self.pushButton_L_zoomOut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/zoom out icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_L_zoomOut.setIcon(icon1)
        self.pushButton_L_zoomOut.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_L_zoomOut.setObjectName("pushButton_L_zoomOut")
        self.gridLayout_16.addWidget(self.pushButton_L_zoomOut, 0, 4, 1, 1)
        self.pushButton_L_zoomIn = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_L_zoomIn.setFont(font)
        self.pushButton_L_zoomIn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/zoom in icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_L_zoomIn.setIcon(icon2)
        self.pushButton_L_zoomIn.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_L_zoomIn.setObjectName("pushButton_L_zoomIn")
        self.gridLayout_16.addWidget(self.pushButton_L_zoomIn, 0, 3, 1, 1)
        self.pushButton_L_rewind = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_L_rewind.setFont(font)
        self.pushButton_L_rewind.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/rewind icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_L_rewind.setIcon(icon3)
        self.pushButton_L_rewind.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_L_rewind.setObjectName("pushButton_L_rewind")
        self.gridLayout_16.addWidget(self.pushButton_L_rewind, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem6, 0, 5, 1, 1)
        self.pushButton_L_stop = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_L_stop.setFont(font)
        self.pushButton_L_stop.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":Ui icons//Ui icons/stop icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_L_stop.setIcon(icon4)
        self.pushButton_L_stop.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_L_stop.setObjectName("pushButton_L_stop")
        self.gridLayout_16.addWidget(self.pushButton_L_stop, 0, 2, 1, 1)
        self.pushButton_L_playPause = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_L_playPause.setFont(font)
        self.pushButton_L_playPause.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/play-pause icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_L_playPause.setIcon(icon5)
        self.pushButton_L_playPause.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_L_playPause.setObjectName("pushButton_L_playPause")
        self.gridLayout_16.addWidget(self.pushButton_L_playPause, 0, 0, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setHorizontalSpacing(7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pushButton_move_plot_L = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_move_plot_L.setFont(font)
        self.pushButton_move_plot_L.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/move to Right icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_move_plot_L.setIcon(icon6)
        self.pushButton_move_plot_L.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_move_plot_L.setObjectName("pushButton_move_plot_L")
        self.gridLayout_17.addWidget(self.pushButton_move_plot_L, 0, 1, 1, 1)
        self.pushButton_L_take_snapshot = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_L_take_snapshot.setFont(font)
        self.pushButton_L_take_snapshot.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/snapshot icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_L_take_snapshot.setIcon(icon7)
        self.pushButton_L_take_snapshot.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_L_take_snapshot.setObjectName("pushButton_L_take_snapshot")
        self.gridLayout_17.addWidget(self.pushButton_L_take_snapshot, 0, 0, 1, 1)
        self.pushButton_L_color = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_L_color.setFont(font)
        self.pushButton_L_color.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/colors icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_L_color.setIcon(icon8)
        self.pushButton_L_color.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_L_color.setObjectName("pushButton_L_color")
        self.gridLayout_17.addWidget(self.pushButton_L_color, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem7, 0, 3, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_17, 1, 0, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setVerticalSpacing(20)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setHorizontalSpacing(30)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setHorizontalSpacing(7)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_L_channels = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.label_L_channels.setFont(font)
        self.label_L_channels.setObjectName("label_L_channels")
        self.gridLayout_19.addWidget(self.label_L_channels, 0, 0, 1, 1)
        self.comboBox_L_channels = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.comboBox_L_channels.setFont(font)
        self.comboBox_L_channels.setObjectName("comboBox_L_channels")
        self.gridLayout_19.addWidget(self.comboBox_L_channels, 0, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setHorizontalSpacing(7)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_L_editLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.label_L_editLabel.setFont(font)
        self.label_L_editLabel.setObjectName("label_L_editLabel")
        self.gridLayout_20.addWidget(self.label_L_editLabel, 0, 0, 1, 1)
        self.lineEdit_L_editLabel = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_L_editLabel.sizePolicy().hasHeightForWidth())
        self.lineEdit_L_editLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.lineEdit_L_editLabel.setFont(font)
        self.lineEdit_L_editLabel.setObjectName("lineEdit_L_editLabel")
        self.gridLayout_20.addWidget(self.lineEdit_L_editLabel, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem8, 0, 2, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_20, 0, 1, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setHorizontalSpacing(25)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalSlider_L_speed = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_L_speed.setMaximum(200)
        self.horizontalSlider_L_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_L_speed.setObjectName("horizontalSlider_L_speed")
        self.gridLayout_21.addWidget(self.horizontalSlider_L_speed, 0, 1, 1, 1)
        # self.lcdNumber_L = QtWidgets.QLCDNumber(self.groupBox_2)
        # self.lcdNumber_L.setObjectName("lcdNumber_L")
        # self.gridLayout_21.addWidget(self.lcdNumber_L, 0, 2, 1, 1)
        self.label_L_speed = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.label_L_speed.setFont(font)
        self.label_L_speed.setObjectName("label_L_speed")
        self.gridLayout_21.addWidget(self.label_L_speed, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem9, 0, 3, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_21, 1, 0, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_31, 1, 0, 1, 1)
        self.gridLayout_55.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.gridLayout_32.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_65 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_65.setObjectName("gridLayout_65")
        self.gridLayout_56 = QtWidgets.QGridLayout()
        self.gridLayout_56.setVerticalSpacing(30)
        self.gridLayout_56.setObjectName("gridLayout_56")
        self.gridLayout_57 = QtWidgets.QGridLayout()
        self.gridLayout_57.setVerticalSpacing(20)
        self.gridLayout_57.setObjectName("gridLayout_57")
        self.gridLayout_58 = QtWidgets.QGridLayout()
        self.gridLayout_58.setHorizontalSpacing(7)
        self.gridLayout_58.setObjectName("gridLayout_58")
        self.pushButton_R_rewind = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_R_rewind.setFont(font)
        self.pushButton_R_rewind.setText("")
        self.pushButton_R_rewind.setIcon(icon3)
        self.pushButton_R_rewind.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_R_rewind.setObjectName("pushButton_R_rewind")
        self.gridLayout_58.addWidget(self.pushButton_R_rewind, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_58.addItem(spacerItem10, 0, 5, 1, 1)
        self.pushButton_R_zoomOut = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_R_zoomOut.setFont(font)
        self.pushButton_R_zoomOut.setText("")
        self.pushButton_R_zoomOut.setIcon(icon1)
        self.pushButton_R_zoomOut.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_R_zoomOut.setObjectName("pushButton_R_zoomOut")
        self.gridLayout_58.addWidget(self.pushButton_R_zoomOut, 0, 4, 1, 1)
        self.pushButton_R_zoomIn = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_R_zoomIn.setFont(font)
        self.pushButton_R_zoomIn.setText("")
        self.pushButton_R_zoomIn.setIcon(icon2)
        self.pushButton_R_zoomIn.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_R_zoomIn.setObjectName("pushButton_R_zoomIn")
        self.gridLayout_58.addWidget(self.pushButton_R_zoomIn, 0, 3, 1, 1)
        self.pushButton_R_playPause = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_R_playPause.setFont(font)
        self.pushButton_R_playPause.setText("")
        self.pushButton_R_playPause.setIcon(icon5)
        self.pushButton_R_playPause.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_R_playPause.setObjectName("pushButton_R_playPause")
        self.gridLayout_58.addWidget(self.pushButton_R_playPause, 0, 0, 1, 1)
        self.pushButton_R_stop = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_R_stop.setFont(font)
        self.pushButton_R_stop.setText("")
        self.pushButton_R_stop.setIcon(icon4)
        self.pushButton_R_stop.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_R_stop.setObjectName("pushButton_R_stop")
        self.gridLayout_58.addWidget(self.pushButton_R_stop, 0, 2, 1, 1)
        self.gridLayout_57.addLayout(self.gridLayout_58, 0, 0, 1, 1)
        self.gridLayout_59 = QtWidgets.QGridLayout()
        self.gridLayout_59.setHorizontalSpacing(7)
        self.gridLayout_59.setObjectName("gridLayout_59")
        self.pushButton_move_plot_R = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_move_plot_R.setFont(font)
        self.pushButton_move_plot_R.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/move to Left icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_move_plot_R.setIcon(icon9)
        self.pushButton_move_plot_R.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_move_plot_R.setObjectName("pushButton_move_plot_R")
        self.gridLayout_59.addWidget(self.pushButton_move_plot_R, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_59.addItem(spacerItem11, 0, 3, 1, 1)
        self.pushButton_R_color = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_R_color.setFont(font)
        self.pushButton_R_color.setText("")
        self.pushButton_R_color.setIcon(icon8)
        self.pushButton_R_color.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_R_color.setObjectName("pushButton_R_color")
        self.gridLayout_59.addWidget(self.pushButton_R_color, 0, 2, 1, 1)
        self.pushButton_R_take_snapshot = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.pushButton_R_take_snapshot.setFont(font)
        self.pushButton_R_take_snapshot.setText("")
        self.pushButton_R_take_snapshot.setIcon(icon7)
        self.pushButton_R_take_snapshot.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_R_take_snapshot.setObjectName("pushButton_R_take_snapshot")
        self.gridLayout_59.addWidget(self.pushButton_R_take_snapshot, 0, 0, 1, 1)
        self.gridLayout_57.addLayout(self.gridLayout_59, 1, 0, 1, 1)
        self.gridLayout_56.addLayout(self.gridLayout_57, 0, 0, 1, 1)
        self.gridLayout_60 = QtWidgets.QGridLayout()
        self.gridLayout_60.setVerticalSpacing(30)
        self.gridLayout_60.setObjectName("gridLayout_60")
        self.gridLayout_61 = QtWidgets.QGridLayout()
        self.gridLayout_61.setHorizontalSpacing(30)
        self.gridLayout_61.setObjectName("gridLayout_61")
        self.gridLayout_62 = QtWidgets.QGridLayout()
        self.gridLayout_62.setHorizontalSpacing(7)
        self.gridLayout_62.setObjectName("gridLayout_62")
        self.label_R_channels = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.label_R_channels.setFont(font)
        self.label_R_channels.setObjectName("label_R_channels")
        self.gridLayout_62.addWidget(self.label_R_channels, 0, 0, 1, 1)
        self.comboBox_R_channels = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.comboBox_R_channels.setFont(font)
        self.comboBox_R_channels.setObjectName("comboBox_R_channels")
        self.gridLayout_62.addWidget(self.comboBox_R_channels, 0, 1, 1, 1)
        self.gridLayout_61.addLayout(self.gridLayout_62, 0, 0, 1, 1)
        self.gridLayout_63 = QtWidgets.QGridLayout()
        self.gridLayout_63.setHorizontalSpacing(7)
        self.gridLayout_63.setObjectName("gridLayout_63")
        self.label_R_editLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.label_R_editLabel.setFont(font)
        self.label_R_editLabel.setObjectName("label_R_editLabel")
        self.gridLayout_63.addWidget(self.label_R_editLabel, 0, 0, 1, 1)
        self.lineEdit_R_editLabel = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_R_editLabel.sizePolicy().hasHeightForWidth())
        self.lineEdit_R_editLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.lineEdit_R_editLabel.setFont(font)
        self.lineEdit_R_editLabel.setObjectName("lineEdit_R_editLabel")
        self.gridLayout_63.addWidget(self.lineEdit_R_editLabel, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_63.addItem(spacerItem12, 0, 2, 1, 1)
        self.gridLayout_61.addLayout(self.gridLayout_63, 0, 1, 1, 1)
        self.gridLayout_60.addLayout(self.gridLayout_61, 0, 0, 1, 1)
        self.gridLayout_64 = QtWidgets.QGridLayout()
        self.gridLayout_64.setHorizontalSpacing(25)
        self.gridLayout_64.setObjectName("gridLayout_64")
        self.label_R_speed = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        self.label_R_speed.setFont(font)
        self.label_R_speed.setObjectName("label_R_speed")
        self.gridLayout_64.addWidget(self.label_R_speed, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_64.addItem(spacerItem13, 0, 3, 1, 1)
        # self.lcdNumber_R = QtWidgets.QLCDNumber(self.groupBox)
        # self.lcdNumber_R.setObjectName("lcdNumber_R")
        # self.gridLayout_64.addWidget(self.lcdNumber_R, 0, 2, 1, 1)
        self.horizontalSlider_R_speed = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_R_speed.setMaximum(200)
        self.horizontalSlider_R_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_R_speed.setObjectName("horizontalSlider_R_speed")
        self.gridLayout_64.addWidget(self.horizontalSlider_R_speed, 0, 1, 1, 1)
        self.gridLayout_60.addLayout(self.gridLayout_64, 1, 0, 1, 1)
        self.gridLayout_56.addLayout(self.gridLayout_60, 1, 0, 1, 1)
        self.gridLayout_65.addLayout(self.gridLayout_56, 0, 0, 1, 1)
        self.gridLayout_32.addWidget(self.groupBox, 2, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_32.addWidget(self.line, 2, 1, 1, 1)
        self.gridLayout_33.addLayout(self.gridLayout_32, 0, 2, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout_33, 1, 0, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_34, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1448, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setGeometry(QtCore.QRect(0, 0, 159, 102))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        self.menuOpen.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/open files icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuOpen.setIcon(icon10)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        self.actionExport.setFont(font)
        self.actionExport.setObjectName("actionExport")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Ui icons/Ui icons/close icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon11)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        self.actionClose.setFont(font)
        self.actionClose.setObjectName("actionClose")
        self.actionGraph_1 = QtWidgets.QAction(MainWindow)
        self.actionGraph_1.setObjectName("actionGraph_1")
        self.actionGraph_2 = QtWidgets.QAction(MainWindow)
        self.actionGraph_2.setObjectName("actionGraph_2")
        self.menuOpen.addAction(self.actionGraph_1)
        self.menuOpen.addAction(self.actionGraph_2)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        # self.horizontalSlider_R_speed.valueChanged['int'].connect(self.lcdNumber_R.display) # type: ignore
        # self.horizontalSlider_L_speed.valueChanged['int'].connect(self.lcdNumber_L.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_MainWindow_title.setText(_translate("MainWindow", "Multi-Channel Signal Viewer "))
        self.groupBox_graph1.setTitle(_translate("MainWindow", "Graph 1"))
        self.groupBox_graph2.setTitle(_translate("MainWindow", "Graph 2"))
        self.pushButton_export.setToolTip(_translate("MainWindow", "Export to PDF"))
        self.pushButton_export.setText(_translate("MainWindow", "Export"))
        self.pushButton_export.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.checkBox_linkGraphs.setToolTip(_translate("MainWindow", "Link the two graphs"))
        self.checkBox_linkGraphs.setText(_translate("MainWindow", "Link"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Control Center"))
        self.pushButton_L_zoomOut.setToolTip(_translate("MainWindow", "Zoom out"))
        self.pushButton_L_zoomIn.setToolTip(_translate("MainWindow", "Zoom in"))
        self.pushButton_L_rewind.setToolTip(_translate("MainWindow", "Rewind"))
        self.pushButton_L_stop.setToolTip(_translate("MainWindow", "Stop"))
        self.pushButton_L_stop.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.pushButton_L_playPause.setToolTip(_translate("MainWindow", "Play/Pause"))
        self.pushButton_move_plot_L.setToolTip(_translate("MainWindow", "Move to the other graph"))
        self.pushButton_L_take_snapshot.setToolTip(_translate("MainWindow", "Take a snapshot of the graph"))
        self.pushButton_L_take_snapshot.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.pushButton_L_color.setToolTip(_translate("MainWindow", "Pick a color for the channel"))
        self.label_L_channels.setText(_translate("MainWindow", "Channels"))
        self.comboBox_L_channels.setToolTip(_translate("MainWindow", "Choose a channel"))
        self.label_L_editLabel.setText(_translate("MainWindow", "Signal name"))
        self.lineEdit_L_editLabel.setToolTip(_translate("MainWindow", "Type the signal name"))
        self.lineEdit_L_editLabel.setPlaceholderText(_translate("MainWindow", "Signal name"))
        self.horizontalSlider_L_speed.setToolTip(_translate("MainWindow", "Change signal speed"))
        # self.lcdNumber_L.setToolTip(_translate("MainWindow", "Signal speed"))
        self.label_L_speed.setText(_translate("MainWindow", "Speed"))
        self.groupBox.setTitle(_translate("MainWindow", "Control Center"))
        self.pushButton_R_rewind.setToolTip(_translate("MainWindow", "Rewind"))
        self.pushButton_R_zoomOut.setToolTip(_translate("MainWindow", "Zoom out"))
        self.pushButton_R_zoomIn.setToolTip(_translate("MainWindow", "Zoom in"))
        self.pushButton_R_playPause.setToolTip(_translate("MainWindow", "Play/Pause"))
        self.pushButton_R_stop.setToolTip(_translate("MainWindow", "Stop"))
        self.pushButton_R_stop.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.pushButton_move_plot_R.setToolTip(_translate("MainWindow", "Move to the other graph"))
        self.pushButton_R_color.setToolTip(_translate("MainWindow", "Pick a color for the channel"))
        self.pushButton_R_take_snapshot.setToolTip(_translate("MainWindow", "Take a snapshot of the graph"))
        self.pushButton_R_take_snapshot.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.label_R_channels.setText(_translate("MainWindow", "Channels"))
        self.comboBox_R_channels.setToolTip(_translate("MainWindow", "Choose a channel"))
        self.label_R_editLabel.setText(_translate("MainWindow", "Signal name"))
        self.lineEdit_R_editLabel.setToolTip(_translate("MainWindow", "Type the signal name"))
        self.lineEdit_R_editLabel.setPlaceholderText(_translate("MainWindow", "Signal name"))
        self.label_R_speed.setText(_translate("MainWindow", "Speed"))
        # self.lcdNumber_R.setToolTip(_translate("MainWindow", "Signal speed"))
        self.horizontalSlider_R_speed.setToolTip(_translate("MainWindow", "Change signal speed"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open..."))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionGraph_1.setText(_translate("MainWindow", "Graph 1"))
        self.actionGraph_2.setText(_translate("MainWindow", "Graph 2"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
